[package]
name = "clone_getters_macro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "clone_getters_macro"
path = "src/lib.rs"
proc-macro = true

[dependencies]
